//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasualActivity
    {
        public long CasualActivityId { get; set; }
        public long BatchId { get; set; }
        public long CasualWorkerId { get; set; }
        public double Quantity { get; set; }
        public long BranchId { get; set; }
        public long SectorId { get; set; }
        public string Notes { get; set; }
        public double Amount { get; set; }
        public bool Deleted { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public long ActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CasualWorker CasualWorker { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Batch Batch { get; set; }
    }
}
