//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasualWorker
    {
        public CasualWorker()
        {
            this.ActivityBatchCasuals = new HashSet<ActivityBatchCasual>();
            this.CasualActivities = new HashSet<CasualActivity>();
            this.Creditors = new HashSet<Creditor>();
            this.Debtors = new HashSet<Debtor>();
            this.AccountTransactionActivities = new HashSet<AccountTransactionActivity>();
        }
    
        public long CasualWorkerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long BranchId { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string NINNumber { get; set; }
        public string NextOfKeen { get; set; }
        public string EmailAddress { get; set; }
        public string UniqueNumber { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<ActivityBatchCasual> ActivityBatchCasuals { get; set; }
        public virtual ICollection<CasualActivity> CasualActivities { get; set; }
        public virtual ICollection<Creditor> Creditors { get; set; }
        public virtual ICollection<Debtor> Debtors { get; set; }
        public virtual ICollection<AccountTransactionActivity> AccountTransactionActivities { get; set; }
    }
}
