//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.BranchSectors = new HashSet<BranchSector>();
            this.Stocks = new HashSet<Stock>();
            this.CasualActivities = new HashSet<CasualActivity>();
            this.StoreStocks = new HashSet<StoreStock>();
            this.StoreMaizeStocks = new HashSet<StoreMaizeStock>();
            this.Inventories = new HashSet<Inventory>();
            this.Creditors = new HashSet<Creditor>();
            this.Debtors = new HashSet<Debtor>();
            this.AccountTransactionActivities = new HashSet<AccountTransactionActivity>();
            this.Transactions = new HashSet<Transaction>();
            this.Cashes = new HashSet<Cash>();
            this.Batches = new HashSet<Batch>();
            this.BatchOutPuts = new HashSet<BatchOutPut>();
            this.FactoryExpenses = new HashSet<FactoryExpense>();
            this.LabourCosts = new HashSet<LabourCost>();
            this.MachineRepairs = new HashSet<MachineRepair>();
            this.OtherExpenses = new HashSet<OtherExpense>();
            this.Utilities = new HashSet<Utility>();
            this.Deliveries = new HashSet<Delivery>();
            this.CashTransfers = new HashSet<CashTransfer>();
        }
    
        public long SectorId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual ICollection<BranchSector> BranchSectors { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<CasualActivity> CasualActivities { get; set; }
        public virtual ICollection<StoreStock> StoreStocks { get; set; }
        public virtual ICollection<StoreMaizeStock> StoreMaizeStocks { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Creditor> Creditors { get; set; }
        public virtual ICollection<Debtor> Debtors { get; set; }
        public virtual ICollection<AccountTransactionActivity> AccountTransactionActivities { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Cash> Cashes { get; set; }
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<BatchOutPut> BatchOutPuts { get; set; }
        public virtual ICollection<FactoryExpense> FactoryExpenses { get; set; }
        public virtual ICollection<LabourCost> LabourCosts { get; set; }
        public virtual ICollection<MachineRepair> MachineRepairs { get; set; }
        public virtual ICollection<OtherExpense> OtherExpenses { get; set; }
        public virtual ICollection<Utility> Utilities { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual ICollection<CashTransfer> CashTransfers { get; set; }
    }
}
