//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreStock
    {
        public long StoreStockId { get; set; }
        public long StockId { get; set; }
        public long ProductId { get; set; }
        public double Quantity { get; set; }
        public double StockBalance { get; set; }
        public long StoreId { get; set; }
        public long BranchId { get; set; }
        public long SectorId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public double StartStock { get; set; }
        public bool SoldOut { get; set; }
        public bool InOrOut { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<double> SoldAmount { get; set; }
        public Nullable<double> Balance { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Store Store { get; set; }
    }
}
