//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.TransactionSubTypes = new HashSet<TransactionSubType>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long TransactionTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<TransactionSubType> TransactionSubTypes { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
